### ISSUE TITLE
How to run from the docker container

### ISSUE THREAD

**Issue by weinix** [paulRbr/terraform-makefile#44]
I build a image with the dockerfile you provided in this repo but not able to use it correctly.
My provider structure:

providers/aws/
├── prod
│   └── empty.tf
├── sandbox
│   ├── empty.tf
│   ├── main.tf
│   └── ~
└── test
    └── test.tf

$ `cat providers/aws/test/test.tf`
provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "example" {
  ami = "ami-08111162"
  instance_type = "t2.micro"
}

$ `docker run  -v providers:/opt/terraform/providers  terraform-make:v1.0  -e provider=aws  -e env=test  dry-run`
Terraform v0.12.0

Your version of Terraform is out of date! The latest version
is 0.12.5. You can update by downloading from www.terraform.io/downloads.html

Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
No changes.`

It seems not able to see the terrafrom script (test.tf) at all
What did  I do wrong?

Thanks for your work!

**Comment by paulRbr** [comment]
Hello @weinix, sorry for the late reply on this issue. Let me try to answer your question.

The `Dockerfile` provided in this repository is here to build the images published on the Docker hub https://hub.docker.com/r/swcc/terraform-makefile.

They are published for each version of terraform publicly so anybody can run it by using `swcc/terraform-makefile:0.12.7` (with the terraform version you wish as tag).

These docker images are mostly useful in a continuous integration environment where the tool pulls your custom terraform configuration within a dedicated environment (usually a docker container). In this way you custom code from `providers/aws/test/...` is available within a container image where `tf-make` command is available.

Of course you can run the docker container yourself as you mention in your question, however be careful to mount your local directory **entirely** as a volume in the container:

    docker run -v `pwd`:/opt/terraform/providers swcc/terraform-makefile:0.12.7 \
               -e provider=aws -e env=test \
               dry-run

(Note the `pwd` execution in the volume parameter)

Hope this helps!

**Comment by weinix** [comment]
Thank you!
I will spend some time to test what you have provided. Thanks again!
